### PR TITLE
Ticket#39 View All Categories

### LINKED ISSUE #39: View All Categories
As an admin I would like to see all the available categories so that I can choose to edit or delete one, or see that I should add a new one.

**Given** an admin is in the app  
**When** they select the `Category Management` link in the menu  
**Then** they should be directed to a page that lists all the Category names ordered alphabetically  

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

### PR DESCRIPTION
**Pull request by SamuelTrevan**
added view all categories
closes #39

### CODE REVIEW

**Comment by tkylesh** [comment]
pull from main after joshua merges his PR, then merge main into this branch and resubmit the PR.

**Review by Leah-Plummer — APPROVED** [review]
Was able to view a list of all categories when "categories" option was selected in nav bar.

**Review by JoshuaJohns — APPROVED** [review]

**Comment by tkylesh** [comment]
@SamuelTrevan add closes# and the issue ticket number so I can see what ticket this is for

**Review by tkylesh — APPROVED** [review]
👍

**Pull request merged**
